### ISSUE TITLE
Export new version to PYPI

### ISSUE THREAD

**Issue by lucabezerra** [vintasoftware/tapioca-twitter#10]
There were some changes made to the code (namely adding the `configuration` endpoint) and the lib hasn't been exported to PYPI since, making it impossible to use those changes when installing the lib from it.

**Comment by chocoelho** [comment]
@filipeximenes is there anything blocking this? Just checking before creating another tag release and sending it to Pypi.

**Comment by filipeximenes** [comment]
Done
